# Generated by Django 3.2 on 2022-07-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ga_session_id', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('page_title', models.CharField(max_length=255)),
                ('time_on_page_in_seconds', models.FloatField()),
                ('total_time', models.FloatField(null=True)),
                ('maxi', models.DateTimeField(null=True)),
                ('mini', models.DateTimeField(null=True)),
                ('all_source', models.CharField(max_length=100, null=True)),
                ('brands', models.CharField(max_length=100, null=True)),
                ('modeles', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
